### ISSUE TITLE
Foreign key constraint failed on the field: `foreign key`

### ISSUE THREAD

**Issue by arvigeus** [kiliman/remix-ecommerce#1]
setup is not working:

```
14 
  15 if (userCount === 0) {
  16   // create default user
→ 17   await prisma.user.create(
  Null constraint violation on the fields: (`id`)
    at RequestHandler.request (/home/arvigeus/Workspace/arvigeus/remix-ecommerce/node_modules/@prisma/client/runtime/index.js:49022:15)
    at async PrismaClient._request (/home/arvigeus/Workspace/arvigeus/remix-ecommerce/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async seed (/home/arvigeus/Workspace/arvigeus/remix-ecommerce/prisma/seed.js:17:5) {
  code: 'P2011',
  clientVersion: '3.15.1',
  meta: { constraint: [ 'id' ] }
}
```

**Comment by kiliman** [comment]
Ah, sorry. I changed the schema to support guest/anonymous shopping carts, but didn't update the seed file. Just remove the user create part for now, then re-run the seed process:
```bash
npx prisma db seed
```
